spinnaker:
  cassandra:
    cluster: 'spinnaker'
    keyspace: 'echo'
  baseUrl: 'http://${DECK_HOST:deck}:9000'

echo:
  baseUrl: 'http://${ECHO_HOST:echo}:8080'

front50:
  baseUrl: 'http://${FRONT50_HOST:front50}:8081'

orca:
  baseUrl: 'http://${ORCA_HOST:orca}:8083'

search:
  index: 'event_history'
